imports:
    - php

filter:
    paths: [src/*, test/*]

build_failure_conditions:
    - 'issues.label("coding-style").exists'
    - 'project.metric("scrutinizer.test_coverage", < 1)'

tools:
    external_code_coverage:
        enabled: true
        timeout: 1800
    php_code_sniffer:
        config:
            standard: PSR2
    php_sim: true
    php_changetracking: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true
