language: php

php:
    - 5.4
    - 5.5

before_script:
    - composer self-update
    - composer install --dev --no-interaction

script:
    - vendor/bin/phpunit -c test/phpunit.xml
    - php .coverage-checker.php build/coverage-clover.xml 100
    - vendor/bin/phpcs --standard=PSR2 -s -p src/ -p test/

after_script:
    - php vendor/bin/coveralls
